name: Karate DSL NPM Runner
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Run Karate tests
      run: npm run test:run
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: karate-reports
        path: target/karate-reports/
